INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (67, '2013-12-02 00:00:00.000000', 19, 'S01E01', '1', 'Pilot');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (68, '2013-12-09 00:00:00.000000', 19, 'S01E02', '2', 'Lawnmower Dog');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (69, '2013-12-16 00:00:00.000000', 24, 'S01E03', '3', 'Anatomy Park');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (70, '2014-01-13 00:00:00.000000', 13, 'S01E04', '4', 'M. Night Shaym-Aliens!');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (71, '2014-01-20 00:00:00.000000', 20, 'S01E05', '5', 'Meeseeks and Destroy');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (72, '2014-01-27 00:00:00.000000', 24, 'S01E06', '6', 'Rick Potion #9');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (73, '2014-03-10 00:00:00.000000', 14, 'S01E07', '7', 'Raising Gazorpazorp');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (74, '2014-03-17 00:00:00.000000', 57, 'S01E08', '8', 'Rixty Minutes');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (75, '2014-03-24 00:00:00.000000', 16, 'S01E09', '9', 'Something Ricked This Way Comes');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (76, '2014-04-07 00:00:00.000000', 60, 'S01E10', '10', 'Close Rick-counters of the Rick Kind');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (77, '2014-04-14 00:00:00.000000', 30, 'S01E11', '11', 'Ricksy Business');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (78, '2015-07-26 00:00:00.000000', 13, 'S02E01', '12', 'A Rickle in Time');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (79, '2015-08-02 00:00:00.000000', 36, 'S02E02', '13', 'Mortynight Run');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (80, '2015-08-09 00:00:00.000000', 14, 'S02E03', '14', 'Auto Erotic Assimilation');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (81, '2015-08-16 00:00:00.000000', 24, 'S02E04', '15', 'Total Rickall');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (82, '2015-08-23 00:00:00.000000', 31, 'S02E05', '16', 'Get Schwifty');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (83, '2015-08-30 00:00:00.000000', 18, 'S02E06', '17', 'The Ricks Must Be Crazy');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (84, '2015-09-13 00:00:00.000000', 26, 'S02E07', '18', 'Big Trouble in Little Sanchez');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (85, '2015-09-20 00:00:00.000000', 40, 'S02E08', '19', 'Interdimensional Cable 2: Tempting Fate');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (86, '2015-09-27 00:00:00.000000', 10, 'S02E09', '20', 'Look Who''s Purging Now');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (87, '2015-10-04 00:00:00.000000', 29, 'S02E10', '21', 'The Wedding Squanchers');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (88, '2017-04-01 00:00:00.000000', 43, 'S03E01', '22', 'The Rickshank Rickdemption');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (89, '2017-07-30 00:00:00.000000', 18, 'S03E02', '23', 'Rickmancing the Stone');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (90, '2017-08-06 00:00:00.000000', 15, 'S03E03', '24', 'Pickle Rick');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (91, '2017-08-13 00:00:00.000000', 30, 'S03E04', '25', 'Vindicators 3: The Return of Worldender');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (92, '2017-08-20 00:00:00.000000', 21, 'S03E05', '26', 'The Whirly Dirly Conspiracy');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (93, '2017-08-27 00:00:00.000000', 19, 'S03E06', '27', 'Rest and Ricklaxation');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (94, '2017-09-10 00:00:00.000000', 65, 'S03E07', '28', 'The Ricklantis Mixup');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (95, '2017-09-17 00:00:00.000000', 20, 'S03E08', '29', 'Morty''s Mind Blowers');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (96, '2017-09-24 00:00:00.000000', 18, 'S03E09', '30', 'The ABC''s of Beth');
INSERT INTO public.episodelog (id, airdate, charactercount, episodecode, episodeid, name) VALUES (97, '2017-10-01 00:00:00.000000', 14, 'S03E10', '31', 'The Rickchurian Mortydate');


INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (99, 2, 31, 'Male', 'Morty Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (100, 3, 24, 'Female', 'Summer Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (101, 4, 24, 'Female', 'Beth Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (102, 5, 21, 'Male', 'Jerry Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (103, 6, 1, 'Female', 'Abadango Cluster Princess', 'Alien', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (104, 7, 2, 'Male', 'Abradolf Lincler', 'Human', 'unknown', 'Genetic experiment');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (105, 8, 1, 'Male', 'Adjudicator Rick', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (106, 9, 1, 'Male', 'Agency Director', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (107, 10, 1, 'Male', 'Alan Rails', 'Human', 'Dead', 'Superhuman (Ghost trains summoner)');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (108, 11, 1, 'Male', 'Albert Einstein', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (109, 12, 1, 'Male', 'Alexander', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (110, 13, 1, 'unknown', 'Alien Googah', 'Alien', 'unknown', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (111, 14, 1, 'Male', 'Alien Morty', 'Alien', 'unknown', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (112, 15, 1, 'Male', 'Alien Rick', 'Alien', 'unknown', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (113, 16, 1, 'Male', 'Amish Cyborg', 'Alien', 'Dead', 'Parasite, Cyborg');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (114, 17, 1, 'Female', 'Annie', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (115, 18, 2, 'Male', 'Antenna Morty', 'Human', 'Alive', 'Human with antennae');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (116, 19, 1, 'Male', 'Antenna Rick', 'Human', 'unknown', 'Human with antennae');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (117, 20, 1, 'Male', 'Ants in my Eyes Johnson', 'Human', 'unknown', 'Human with ants in his eyes');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (118, 21, 2, 'Male', 'Aqua Morty', 'Humanoid', 'unknown', 'Fish-Person');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (119, 22, 3, 'Male', 'Aqua Rick', 'Humanoid', 'unknown', 'Fish-Person');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (120, 23, 5, 'Male', 'Arcade Alien', 'Alien', 'unknown', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (121, 24, 1, 'Male', 'Armagheadon', 'Alien', 'Alive', 'Cromulon');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (122, 25, 1, 'Male', 'Armothy', 'unknown', 'Dead', 'Self-aware arm');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (123, 26, 1, 'Female', 'Arthricia', 'Alien', 'Alive', 'Cat-Person');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (124, 27, 2, 'Male', 'Artist Morty', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (125, 28, 3, 'Male', 'Attila Starwar', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (126, 29, 1, 'Male', 'Baby Legs', 'Human', 'Alive', 'Human with baby legs');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (127, 30, 1, 'Male', 'Baby Poopybutthole', 'Poopybutthole', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (128, 31, 1, 'Male', 'Baby Wizard', 'Alien', 'Dead', 'Parasite');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (129, 32, 1, 'Female', 'Bearded Lady', 'Alien', 'Dead', 'Parasite');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (130, 33, 1, 'Male', 'Beebo', 'Alien', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (131, 34, 3, 'Male', 'Benjamin', 'Poopybutthole', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (132, 35, 4, 'unknown', 'Bepisian', 'Alien', 'Alive', 'Bepisian');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (133, 36, 1, 'unknown', 'Beta-Seven', 'Alien', 'Alive', 'Hivemind');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (134, 37, 1, 'Female', 'Beth Sanchez', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (135, 38, 7, 'Female', 'Beth Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (136, 39, 1, 'Female', 'Beth Smith', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (137, 40, 1, 'Female', 'Beth''s Mytholog', 'Mytholog', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (138, 41, 1, 'Female', 'Big Boobed Waitress', 'Humanoid', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (139, 42, 1, 'Male', 'Big Head Morty', 'Human', 'unknown', 'Human with giant head');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (140, 43, 1, 'Male', 'Big Morty', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (141, 44, 1, 'Male', 'Body Guard Morty', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (142, 45, 1, 'Male', 'Bill', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (143, 46, 1, 'Male', 'Bill', 'Animal', 'unknown', 'Dog');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (144, 47, 5, 'Male', 'Birdperson', 'Alien', 'Dead', 'Bird-Person');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (145, 48, 2, 'Male', 'Black Rick', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (146, 49, 1, 'unknown', 'Blamph', 'Alien', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (147, 50, 1, 'Male', 'Blim Blam', 'Alien', 'Alive', 'Korblock');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (148, 51, 1, 'Male', 'Blue Diplomat', 'Alien', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (149, 52, 1, 'Male', 'Blue Footprint Guy', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (150, 53, 1, 'Male', 'Blue Shirt Morty', 'Human', 'unknown', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (151, 54, 1, 'Male', 'Bobby Moynihan', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (152, 55, 2, 'unknown', 'Boobloosian', 'Alien', 'Dead', 'Boobloosian');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (153, 56, 1, 'Male', 'Bootleg Portal Chemist Rick', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (154, 57, 1, 'Male', 'Borpocian', 'Alien', 'Alive', 'Elephant-Person');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (155, 58, 3, 'Male', 'Brad', 'Human', 'Alive', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (156, 59, 1, 'Male', 'Brad Anderson', 'Human', 'Dead', '');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (157, 60, 1, 'Female', 'Calypso', 'Human', 'Dead', 'Superhuman');
INSERT INTO public.characterlog (id, characterid, episodelist, gender, name, species, status, type) VALUES (98, 1, 31, 'Male', 'Ayodeji Ilori', 'Human', 'Alive', '');



INSERT INTO public.commentlog (id, comment, createtime, ipaddress) VALUES (158, 'This is my first comment', '2019-10-19 12:07:44.483000', '0:0:0:0:0:0:0:1');
INSERT INTO public.commentlog (id, comment, createtime, ipaddress) VALUES (159, 'This is my second comment', '2019-10-19 12:08:42.906000', '0:0:0:0:0:0:0:1');

INSERT INTO public.episodelog_commentlog (episodelog_id, commentlogentitylist_id) VALUES (67, 158);
INSERT INTO public.episodelog_commentlog (episodelog_id, commentlogentitylist_id) VALUES (67, 159);